CXX = g++
CC = g++

CXXFLAGS = -Wall -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m
LDFLAGS = -L/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/config-3.6m-darwin -lpython3.6m

all: main

main: main.o

clean:
	rm -f *.o main
